-- MySQL Script generated by MySQL Workbench
-- Fri Mar 29 18:22:01 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbdelivery
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbdelivery
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbdelivery` DEFAULT CHARACTER SET utf8 ;
USE `dbdelivery` ;

-- -----------------------------------------------------
-- Table `dbdelivery`.`tbl_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdelivery`.`tbl_usuario` (
  `usu_id` INT NOT NULL AUTO_INCREMENT,
  `usu_nome` VARCHAR(100) NOT NULL,
  `usu_login` VARCHAR(80) NOT NULL,
  `usu_senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`usu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbdelivery`.`tbl_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdelivery`.`tbl_cliente` (
  `cli_id` INT NOT NULL AUTO_INCREMENT,
  `cli_telefone` VARCHAR(20) NOT NULL,
  `cli_nome` VARCHAR(80) NOT NULL,
  `cli_cpf_cnpj` VARCHAR(45) NULL,
  `cli_email` VARCHAR(100) NULL,
  `cli_observacao` VARCHAR(255) NULL,
  `cli_endereco` VARCHAR(120) NULL,
  `cli_numero` VARCHAR(5) NULL,
  `cli_complemento` VARCHAR(45) NULL,
  `cli_bairro` VARCHAR(100) NULL,
  `cli_cidade` VARCHAR(100) NULL,
  `cli_estado` VARCHAR(2) NULL,
  `cli_cep` VARCHAR(10) NULL,
  `cli_taxa_de_entrega` DECIMAL(25,2) NULL,
  PRIMARY KEY (`cli_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbdelivery`.`tbl_status_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdelivery`.`tbl_status_pedido` (
  `sta_ped_id` INT NOT NULL AUTO_INCREMENT,
  `sta_ped_descricao` VARCHAR(100) NULL,
  PRIMARY KEY (`sta_ped_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbdelivery`.`tbl_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdelivery`.`tbl_pagamento` (
  `pag_id` INT NOT NULL AUTO_INCREMENT,
  `pag_descricao` VARCHAR(100) NULL,
  PRIMARY KEY (`pag_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbdelivery`.`tbl_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdelivery`.`tbl_pedido` (
  `ped_id` INT NOT NULL AUTO_INCREMENT,
  `ped_data` DATE NOT NULL,
  `ped_valor_bruto` DECIMAL(25,2) NOT NULL,
  `ped_desconto` DECIMAL(25,2) NOT NULL,
  `ped_cli_id` INT NOT NULL,
  `ped_sta_ped_id` INT NOT NULL,
  `ped_usu_id` INT NOT NULL,
  `ped_pag_id` INT NOT NULL,
  PRIMARY KEY (`ped_id`, `ped_cli_id`, `ped_sta_ped_id`, `ped_usu_id`, `ped_pag_id`),
  INDEX `fk_tbl_pedido_tbl_cliente_idx` (`ped_cli_id` ASC),
  INDEX `fk_tbl_pedido_tbl_status_pedido1_idx` (`ped_sta_ped_id` ASC),
  INDEX `fk_tbl_pedido_tbl_usuario1_idx` (`ped_usu_id` ASC),
  INDEX `fk_tbl_pedido_tbl_pagamento1_idx` (`ped_pag_id` ASC),
  CONSTRAINT `fk_tbl_pedido_tbl_cliente`
    FOREIGN KEY (`ped_cli_id`)
    REFERENCES `dbdelivery`.`tbl_cliente` (`cli_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_pedido_tbl_status_pedido1`
    FOREIGN KEY (`ped_sta_ped_id`)
    REFERENCES `dbdelivery`.`tbl_status_pedido` (`sta_ped_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_pedido_tbl_usuario1`
    FOREIGN KEY (`ped_usu_id`)
    REFERENCES `dbdelivery`.`tbl_usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_pedido_tbl_pagamento1`
    FOREIGN KEY (`ped_pag_id`)
    REFERENCES `dbdelivery`.`tbl_pagamento` (`pag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbdelivery`.`tbl_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdelivery`.`tbl_produto` (
  `pro_id` INT NOT NULL AUTO_INCREMENT,
  `pro_nome` VARCHAR(100) NOT NULL,
  `pro_valor_custo` DECIMAL(25,2) NOT NULL,
  `pro_valor_venda` DECIMAL(25,2) NOT NULL,
  `pro_estoque` INT NOT NULL,
  PRIMARY KEY (`pro_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbdelivery`.`tbl_produtos_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbdelivery`.`tbl_produtos_pedido` (
  `pro_ped_id` INT NOT NULL AUTO_INCREMENT,
  `pro_ped_valor` DECIMAL(25,2) NOT NULL,
  `pro_ped_quatidade` INT NOT NULL,
  `pro_ped_ped_id` INT NOT NULL,
  `pro_ped_cli_id` INT NOT NULL,
  `pro_ped_pro_id` INT NOT NULL,
  PRIMARY KEY (`pro_ped_id`, `pro_ped_ped_id`, `pro_ped_cli_id`, `pro_ped_pro_id`),
  INDEX `fk_tbl_pedido_tbl_pedido1_idx` (`pro_ped_ped_id` ASC, `pro_ped_cli_id` ASC),
  INDEX `fk_tbl_pedido_tbl_produto1_idx` (`pro_ped_pro_id` ASC),
  CONSTRAINT `fk_tbl_pedido_tbl_pedido1`
    FOREIGN KEY (`pro_ped_ped_id` , `pro_ped_cli_id`)
    REFERENCES `dbdelivery`.`tbl_pedido` (`ped_id` , `ped_cli_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_pedido_tbl_produto1`
    FOREIGN KEY (`pro_ped_pro_id`)
    REFERENCES `dbdelivery`.`tbl_produto` (`pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
